### ISSUE TITLE
installation error on xbtit

### ISSUE THREAD

**Issue by tojoaijo** [imtiazmahbub/XBTIT-IMDB-Grabber#1]
Hello,
I tried to install this hack and I have this error (see attachment)
I don't know what is the file to chmod manually.
![hack_imdb](https://user-images.githubusercontent.com/5299914/31484284-5ce1260c-af38-11e7-95c3-718a10d88e4a.PNG)

**Comment by imtiazmahbub** [comment]
you have to manually chmod the folders. Or:

1. remove lines after:
`<!-- Copy files-->`
till `</hack>`

2. And then manually copy the files of `imdb-files` into your xbtit root directory.
3. also copy `imdb-files/imdbController.php` into xbtit root directory.

**Comment by tojoaijo** [comment]
I have changed the files like you say and the installation was finished correctly.
But when I go to view the list of torrent on the website, it's said that the table doesn't exist (see mysql error on attachement). It's seems that the script of the hacks doesn't created the table on the database, I checked in the database and the table does not exist.
So I tried to create manually the table on the database like on the script and I have this error (see attachement)
![imdb-sql1](https://user-images.githubusercontent.com/5299914/31532915-ad6b51ea-aff8-11e7-8444-6410150b150b.PNG)
![imdb-sql](https://user-images.githubusercontent.com/5299914/31532916-ada0a3b8-aff8-11e7-9472-1f6afeebab60.PNG)

**Comment by imtiazmahbub** [comment]
what mysql version are you using?
See this answer on [stackoverflow.com](https://stackoverflow.com/a/23153922/1469223)

**Comment by tojoaijo** [comment]
I use mysql 5.5.57
![mysql](https://user-images.githubusercontent.com/5299914/31597122-5511513a-b24f-11e7-98da-8d52eafd05d6.PNG)

**Comment by imtiazmahbub** [comment]
Did you follow the stackoverflow link? you can solve your problem by either:
1. by upgrading your mysql version
2. Changing the following line: `last_update datetime` into `last_update TIMESTAMP`

**Comment by tojoaijo** [comment]
I have changed my system to use mysql 5.6, so it's working fine now.
Thank you for your help and your good work :)
